version: '2'
services:
    rec_api:
        build:
            context: .
            args:
                PORT: "8910"
                WORKERS: "4"
                TIMEOUT: "30"
        ports: 
            - "8910:8910"
        depends_on:
            - mongo
        environment:
            - REC_API_CONFIG=/code/config.py
    mongo:
        image: "mongo"
